// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8llAQnA5661XySw1eiq2BZpCRcGnXmWg',
    appId: '1:486165213730:web:b81dba2eb68d3a18d7907b',
    messagingSenderId: '486165213730',
    projectId: 'ecohome-437cf',
    authDomain: 'ecohome-437cf.firebaseapp.com',
    storageBucket: 'ecohome-437cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApIUv0sdqmkR0iv3aBmfskIP5oMgMfxtc',
    appId: '1:486165213730:android:f2e79a16195ecfa1d7907b',
    messagingSenderId: '486165213730',
    projectId: 'ecohome-437cf',
    storageBucket: 'ecohome-437cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW-R8JZK4k7nXCwvkn_ZSFHfb336SC7xw',
    appId: '1:486165213730:ios:a9a7abf7373bbb85d7907b',
    messagingSenderId: '486165213730',
    projectId: 'ecohome-437cf',
    storageBucket: 'ecohome-437cf.firebasestorage.app',
    iosBundleId: 'com.example.ecohomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW-R8JZK4k7nXCwvkn_ZSFHfb336SC7xw',
    appId: '1:486165213730:ios:a9a7abf7373bbb85d7907b',
    messagingSenderId: '486165213730',
    projectId: 'ecohome-437cf',
    storageBucket: 'ecohome-437cf.firebasestorage.app',
    iosBundleId: 'com.example.ecohomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8llAQnA5661XySw1eiq2BZpCRcGnXmWg',
    appId: '1:486165213730:web:f7dc3ebc6203d71cd7907b',
    messagingSenderId: '486165213730',
    projectId: 'ecohome-437cf',
    authDomain: 'ecohome-437cf.firebaseapp.com',
    storageBucket: 'ecohome-437cf.firebasestorage.app',
  );
}
